In [ ]:
import pandas as pd
import numpy as np

# Load the data
data = pd.read_csv('/home/nalin21478/BTP/ML-food-Processing/Numerical_Textual_ML/Data/65_Nuts.csv',index_col=0)

In [ ]:
data.head()

In [ ]:
data["Main_food_description"]

In [ ]:
data

In [ ]:
data.columns


In [ ]:
import torch
import numpy as np
import pandas as pd
from transformers import DistilBertTokenizer, DistilBertModel

# Assuming data is your DataFrame containing both categorical and numerical data

# Step 1: Separate Categorical and Numerical Data
categorical_data = data.select_dtypes(include=['object'])
numerical_data = data.select_dtypes(exclude=['object'])

# Initialize DistilBERT tokenizer and model
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertModel.from_pretrained('distilbert-base-uncased')

In [ ]:
import torch
import numpy as np
import pandas as pd
from transformers import DistilBertTokenizer, DistilBertModel


# Separate Categorical and Numerical Data
categorical_data = data.select_dtypes(include=['object'])
numerical_data = data.select_dtypes(exclude=['object'])

# Initialize DistilBERT tokenizer and model
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertModel.from_pretrained('distilbert-base-uncased')

# Function to tokenize and obtain embeddings for a single value
def get_embeddings(value):
    inputs = tokenizer(value, return_tensors='pt', padding=True, truncation=True)
    outputs = model(**inputs)
    embeddings = torch.mean(outputs.last_hidden_state, dim=1).squeeze().detach().numpy()
    return embeddings

# Function to obtain embeddings for each value in a categorical column
def get_column_embeddings(column):
    embeddings_list = []
    for value in column:
        embeddings = get_embeddings(value)
        embeddings_list.append(embeddings)
    return embeddings_list

# Dictionary to store aggregated embeddings for each categorical column
categorical_embeddings_aggregated = {}

# Generate Word Embeddings for Categorical Data
for col in categorical_data.columns:
    print(f'Obtaining embeddings for {col}...')
    # Obtain embeddings for values in the column
    embeddings = get_column_embeddings(categorical_data[col])
    # Aggregate embeddings (e.g., average pooling)
    aggregated_embeddings = np.mean(embeddings, axis=0)
    # Store aggregated embeddings in the dictionary
    categorical_embeddings_aggregated[col] = aggregated_embeddings

# Convert categorical_embeddings_aggregated dictionary to DataFrame
categorical_embeddings_df = pd.DataFrame(categorical_embeddings_aggregated)



## Combine Numerical and Categorical Data with Embeddings
data_with_embeddings = pd.concat([numerical_data.reset_index(drop=True), categorical_embeddings_df.reset_index(drop=True)], axis=1)



In [ ]:
data.shape

In [29]:
data_with_embeddings

catnumb  novaclass  Protein  Total Fat  Carbohydrate  Energy  Alcohol  \
0        9602          1     1.03       4.38          6.89    70.0      0.0   
1        1004          1     3.28       1.91          4.85    50.0      0.0   
2        1002          1     3.15       3.25          4.80    61.0      0.0   
3        1002          1     3.10       3.46          4.46    61.0      0.0   
4        1002          1     3.14       3.24          4.79    61.0      0.0   
...       ...        ...      ...        ...           ...     ...      ...   
2965     7802          4     0.00       0.00          0.15     1.0      0.0   
2966     7802          4     0.00       0.00          4.50    18.0      0.0   
2967     7804          4     0.00       0.00          1.22     5.0      0.0   
2968     7804          4     0.00       0.00          5.49    22.0      0.0   
2969     9204          1     0.00       0.00          0.00     0.0      0.0   

      Water  Caffeine  Theobromine  ...  18:4   20:1  20:5 n-3  22:1  \
0     87.50       0.0          0.0  ...   0.0  0.040       0.0   0.0   
1     89.25       0.0          0.0  ...   0.0  0.001       0.0   0.0   
2     88.13       0.0          0.0  ...   0.0  0.000       0.0   0.0   
3     88.20       0.0          0.0  ...   0.0  0.000       0.0   0.0   
4     87.87       0.0          0.0  ...   0.0  0.000       0.0   0.0   
...     ...       ...          ...  ...   ...    ...       ...   ...   
2965  99.85       0.0          0.0  ...   0.0  0.000       0.0   0.0   
2966  94.44       0.0          0.0  ...   0.0  0.000       0.0   0.0   
2967  98.78       0.0          0.0  ...   0.0  0.000       0.0   0.0   
2968  94.44       0.0          0.0  ...   0.0  0.000       0.0   0.0   
2969  99.98       0.0          0.0  ...   0.0  0.000       0.0   0.0   

      22:5 n-3  Fatty acids, total monounsaturated  \
0          0.0                               1.658   
1          0.0                               0.507   
2          0.0                               0.812   
3          0.0                               0.999   
4          0.0                               0.810   
...        ...                                 ...   
2965       0.0                               0.000   
2966       0.0                               0.000   
2967       0.0                               0.000   
2968       0.0                               0.000   
2969       0.0                               0.000   

      Fatty acids, total polyunsaturated  Main_food_description   catname  \
0                                  0.497               0.005968  0.092892   
1                                  0.094               0.028462  0.085337   
2                                  0.195              -0.000871 -0.140204   
3                                  0.128               0.172098  0.191872   
4                                  0.194               0.201337  0.154887   
...                                  ...                    ...       ...   
2965                               0.000               0.000000  0.000000   
2966                               0.000               0.000000  0.000000   
2967                               0.000               0.000000  0.000000   
2968                               0.000               0.000000  0.000000   
2969                               0.000               0.000000  0.000000   

      macroclass  
0       0.161031  
1      -0.057516  
2      -0.293136  
3       0.052279  
4      -0.034462  
...          ...  
2965    0.000000  
2966    0.000000  
2967    0.000000  
2968    0.000000  
2969    0.000000  

[2970 rows x 70 columns]

In [30]:
data_with_embeddings["novaclass"].value_counts()

novaclass
4    2112
3     466
1     339
2      53
Name: count, dtype: int64

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, matthews_corrcoef
from imblearn.over_sampling import SMOTE

# Assuming you have a target column named 'novaclass' in your original DataFrame
# Split data into features (X) and target (y)
X = data_with_embeddings.drop(columns=['novaclass'])  # Features
y = data_with_embeddings['novaclass']  # Target

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
from sklearn.impute import SimpleImputer



# Apply SMOTE to the training data after handling missing values
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)



# Initialize and train a Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100)
rf_classifier.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred = rf_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Print F1 score and Matthews correlation coefficient
print("F1 Score (weighted):", f1_score(y_test, y_pred, average='weighted'))
print("Matthews Correlation Coefficient:", matthews_corrcoef(y_test, y_pred))


Accuracy: 0.9259259259259259
Confusion Matrix:
[[ 62   0   4   2]
 [  0   6   0   2]
 [  5   0  71  11]
 [  6   5   9 411]]

Classification Report:
              precision    recall  f1-score   support

           1       0.85      0.91      0.88        68
           2       0.55      0.75      0.63         8
           3       0.85      0.82      0.83        87
           4       0.96      0.95      0.96       431

    accuracy                           0.93       594
   macro avg       0.80      0.86      0.83       594
weighted avg       0.93      0.93      0.93       594

F1 Score (weighted): 0.9267635752587424
Matthews Correlation Coefficient: 0.8336403847944476


In [33]:
from sklearn.impute import SimpleImputer
from sklearn.ensemble import ExtraTreesClassifier


# Initialize and train an ExtraTreesClassifier
et_classifier = ExtraTreesClassifier(n_estimators=100, random_state=42)
et_classifier.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred = et_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Print F1 score and Matthews correlation coefficient
print("F1 Score (weighted):", f1_score(y_test, y_pred, average='weighted'))
print("Matthews Correlation Coefficient:", matthews_corrcoef(y_test, y_pred))


Accuracy: 0.930976430976431
Confusion Matrix:
[[ 61   0   5   2]
 [  0   6   0   2]
 [  6   0  72   9]
 [  7   3   7 414]]

Classification Report:
              precision    recall  f1-score   support

           1       0.82      0.90      0.86        68
           2       0.67      0.75      0.71         8
           3       0.86      0.83      0.84        87
           4       0.97      0.96      0.97       431

    accuracy                           0.93       594
   macro avg       0.83      0.86      0.84       594
weighted avg       0.93      0.93      0.93       594

F1 Score (weighted): 0.9314188920195349
Matthews Correlation Coefficient: 0.844479188769997


/home/nalin21478/miniconda3/envs/torch/lib/python3.11/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but ExtraTreesClassifier was fitted without feature names
  warnings.warn(


In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, matthews_corrcoef
from imblearn.over_sampling import SMOTE
from lightgbm import LGBMClassifier



# Initialize and train an LightGBM classifier
lgbm_classifier = LGBMClassifier(random_state=42)
lgbm_classifier.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred = lgbm_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Print F1 score and Matthews correlation coefficient
print("F1 Score (weighted):", f1_score(y_test, y_pred, average='weighted'))
print("Matthews Correlation Coefficient:", matthews_corrcoef(y_test, y_pred))


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006612 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 16273
[LightGBM] [Info] Number of data points in the train set: 6724, number of used features: 69
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Accuracy: 0.930976430976431
Confusion Matrix:
[[ 63   0   3   2]
 [  1   6   0   1]
 [  6   0  68  13]
 [  6   2   7 416]]

Classification Report:
              precision    recall  f1-score   support

           1       0.83      0.93      0.88        68
           2       0.75      0.75      0.75         8
           3       0.87      0.78      0.82        87
           4       0.96      0.97      0.96       431

 

In [35]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, matthews_corrcoef
from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer


# Initialize and train a Gradient Boosting Classifier
gb_classifier = GradientBoostingClassifier(random_state=42)
gb_classifier.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred = gb_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Print F1 score and Matthews correlation coefficient
print("F1 Score (weighted):", f1_score(y_test, y_pred, average='weighted'))
print("Matthews Correlation Coefficient:", matthews_corrcoef(y_test, y_pred))


Accuracy: 0.9175084175084175
Confusion Matrix:
[[ 66   0   2   0]
 [  1   6   0   1]
 [  5   0  71  11]
 [  8   4  17 402]]

Classification Report:
              precision    recall  f1-score   support

           1       0.82      0.97      0.89        68
           2       0.60      0.75      0.67         8
           3       0.79      0.82      0.80        87
           4       0.97      0.93      0.95       431

    accuracy                           0.92       594
   macro avg       0.80      0.87      0.83       594
weighted avg       0.92      0.92      0.92       594

F1 Score (weighted): 0.9189666096228462
Matthews Correlation Coefficient: 0.8209853585063333


/home/nalin21478/miniconda3/envs/torch/lib/python3.11/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but GradientBoostingClassifier was fitted without feature names
  warnings.warn(


In [39]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, matthews_corrcoef
from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer

y_train_xg=y_train-1
y_test_xg=y_test-1
import xgboost as xgb



# Apply SMOTE to the training data after handling missing values
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train_xg)

# Initialize and train a XGBoost Classifier
xgb_classifier = xgb.XGBClassifier(random_state=42)
xgb_classifier.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred = xgb_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test_xg, y_pred)
print("Accuracy:", accuracy)

# Print confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test_xg, y_pred))
print("\nClassification Report:")
print(classification_report(y_test_xg, y_pred))

# Print F1 score and Matthews correlation coefficient
print("F1 Score (weighted):", f1_score(y_test_xg, y_pred, average='weighted'))
print("Matthews Correlation Coefficient:", matthews_corrcoef(y_test_xg, y_pred))



Accuracy: 0.9326599326599326
Confusion Matrix:
[[ 64   0   2   2]
 [  1   6   0   1]
 [  5   0  68  14]
 [  5   3   7 416]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.94      0.90        68
           1       0.67      0.75      0.71         8
           2       0.88      0.78      0.83        87
           3       0.96      0.97      0.96       431

    accuracy                           0.93       594
   macro avg       0.84      0.86      0.85       594
weighted avg       0.93      0.93      0.93       594

F1 Score (weighted): 0.932150791567532
Matthews Correlation Coefficient: 0.8464839012170764


In [41]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, matthews_corrcoef
from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer


# Apply SMOTE to the training data after handling missing values
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Initialize and train a Gradient Boosting Classifier
gb_classifier = DecisionTreeClassifier(random_state=42)
gb_classifier.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred = gb_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Print F1 score and Matthews correlation coefficient
print("F1 Score (weighted):", f1_score(y_test, y_pred, average='weighted'))
print("Matthews Correlation Coefficient:", matthews_corrcoef(y_test, y_pred))


Accuracy: 0.877104377104377
Confusion Matrix:
[[ 55   0   8   5]
 [  1   5   0   2]
 [  8   0  63  16]
 [ 10   5  18 398]]

Classification Report:
              precision    recall  f1-score   support

           1       0.74      0.81      0.77        68
           2       0.50      0.62      0.56         8
           3       0.71      0.72      0.72        87
           4       0.95      0.92      0.93       431

    accuracy                           0.88       594
   macro avg       0.72      0.77      0.75       594
weighted avg       0.88      0.88      0.88       594

F1 Score (weighted): 0.8789157461176953
Matthews Correlation Coefficient: 0.7269964168520642


In [42]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, matthews_corrcoef
from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer



# Initialize and train a Gradient Boosting Classifier
gb_classifier = KNeighborsClassifier()
gb_classifier.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred = gb_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Print F1 score and Matthews correlation coefficient
print("F1 Score (weighted):", f1_score(y_test, y_pred, average='weighted'))
print("Matthews Correlation Coefficient:", matthews_corrcoef(y_test, y_pred))


Accuracy: 0.8922558922558923
Confusion Matrix:
[[ 64   0   4   0]
 [  0   7   1   0]
 [  8   0  73   6]
 [  9  11  25 386]]

Classification Report:
              precision    recall  f1-score   support

           1       0.79      0.94      0.86        68
           2       0.39      0.88      0.54         8
           3       0.71      0.84      0.77        87
           4       0.98      0.90      0.94       431

    accuracy                           0.89       594
   macro avg       0.72      0.89      0.78       594
weighted avg       0.91      0.89      0.90       594

F1 Score (weighted): 0.8987677564108959
Matthews Correlation Coefficient: 0.782625437865471


In [43]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, matthews_corrcoef
from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer


# Initialize and train a Gradient Boosting Classifier
gb_classifier = MLPClassifier()
gb_classifier.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred = gb_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Print F1 score and Matthews correlation coefficient
print("F1 Score (weighted):", f1_score(y_test, y_pred, average='weighted'))
print("Matthews Correlation Coefficient:", matthews_corrcoef(y_test, y_pred))


Accuracy: 0.7575757575757576
Confusion Matrix:
[[ 38   8  21   1]
 [  0   7   0   1]
 [  3   7  74   3]
 [  4  69  27 331]]

Classification Report:
              precision    recall  f1-score   support

           1       0.84      0.56      0.67        68
           2       0.08      0.88      0.14         8
           3       0.61      0.85      0.71        87
           4       0.99      0.77      0.86       431

    accuracy                           0.76       594
   macro avg       0.63      0.76      0.60       594
weighted avg       0.90      0.76      0.81       594

F1 Score (weighted): 0.8088735258352057
Matthews Correlation Coefficient: 0.5927561380550449


In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, matthews_corrcoef
from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer



# Initialize and train a Gradient Boosting Classifier
gb_classifier = LogisticRegression()
gb_classifier.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred = gb_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Print F1 score and Matthews correlation coefficient
print("F1 Score (weighted):", f1_score(y_test, y_pred, average='weighted'))
print("Matthews Correlation Coefficient:", matthews_corrcoef(y_test, y_pred))


Accuracy: 0.5959595959595959
Confusion Matrix:
[[ 61   4   3   0]
 [  3   4   1   0]
 [ 21   7  52   7]
 [ 36  61  97 237]]

Classification Report:
              precision    recall  f1-score   support

           1       0.50      0.90      0.65        68
           2       0.05      0.50      0.10         8
           3       0.34      0.60      0.43        87
           4       0.97      0.55      0.70       431

    accuracy                           0.60       594
   macro avg       0.47      0.64      0.47       594
weighted avg       0.81      0.60      0.65       594

F1 Score (weighted): 0.6481714855788929
Matthews Correlation Coefficient: 0.4221546194338563


/home/nalin21478/miniconda3/envs/torch/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [45]:
data_with_embeddings.to_csv('/home/nalin21478/BTP/ML-food-Processing/Numerical_Textual_ML/Data/65 Nuts/65_Nuts_Embeddings_DistilBert.csv')